services:
  # Banco de dados MySQL para o Zabbix Server
  mysql-server:
    image: mysql:8.0
    container_name: zabbix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - zabbix-network

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    volumes:
      - zbx-db-backup:/var/lib/zabbix/backups
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server
    networks:
      - zabbix-network

  # Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

  # Zabbix Agent 2
  zabbix-agent2:
    image: zabbix/zabbix-agent2
    container_name: zabbix-agent2
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: "10051"
    networks:
      - zabbix-network

  # Grafana para visualização de dados do Zabbix
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  zbx-db-backup:
    driver: local
  grafana-data:
    driver: local
